---

- name: Set the correct timezone.
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

# Debian family OSes also have an /etc/timezone file.
- name: Set timezone in /etc/timezone file.
  template:
    src: timezone.j2
    dest: /etc/timezone
    force: yes

- name: Install NTP (Debian).
  apt: name=ntp state=installed

- name: Ensure NTP is running and enabled as configured.
  service:
    name: ntp
    state: started
    enabled: yes

- name: Generate ntp.conf file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf

- name: restart ntp
  service: name=ntp state=restarted
