---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: varMyClusterRoleBinding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: Role
  name: varMyClusterRoleBinding 
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: monitoringvarClusterRoleBinding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
roleRef:
  kind: Role
  name: monitoringvarClusterRoleBinding
  apiGroup: rbac.authorization.k8s.io
