---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs-pv
  labels:
    group: monitoring 
    type: nfs
    role: prometheus
spec:
  capacity:
    storage: ${PROM_PV_SIZE}
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER}
    path: "${NFS_ROOT}/${CLUSTER_ID}/prom"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-nfs-pvc
  namespace: monitoring 
  labels:
    group: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${PROM_PV_SIZE}
  selector:
    matchLabels:
      type: nfs
      group: monitoring
      role: prometheus

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-nfs-pv
  labels:
    group: monitoring 
    type: nfs
    role: prometheus-alertmanager
spec:
  capacity:
      storage: ${PROM_PV_SIZE}
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER}
    path: "${NFS_ROOT}/${CLUSTER_ID}/alertmanager"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager-nfs-pvc
  namespace: monitoring 
  labels:
    group: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${PROM_PV_SIZE}
  selector:
    matchLabels:
      type: nfs
      group: monitoring
      role: prometheus-alertmanager

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage-nfs-pv
  labels:
    group: monitoring 
    type: nfs
    role: grafana-storage
spec:
  capacity:
    storage: ${PROM_PV_SIZE}
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER}
    path: "${NFS_ROOT}/${CLUSTER_ID}/grafana"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-nfs-pvc
  namespace: monitoring 
  labels:
    group: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs
      group: monitoring
      role: grafana-storage

