apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: kube-system
  labels:
    component: elasticsearch
    role: master
    group: system
spec:
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        group: system
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
         {
         "name": "sysctl",
           "image": "busybox",
           "imagePullPolicy":"IfNotPresent",
           "command": ["sysctl", "-w", "vm.max_map_count=262144"],
           "securityContext": {
             "privileged": true
           }
         }
        ]'
    spec:
      containers:
      - name: elasticsearch-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "logging-es"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: NUMBER_OF_MASTERS
          value: "${LOGGING_ES_MINIMUM_MASTERS}"
        - name: ES_JAVA_OPTS
          value: "-Xms${LOGGING_ES_JAVA_HEAP_SIZE} -Xmx${LOGGING_ES_JAVA_HEAP_SIZE}"
        - name: "MAX_LOCAL_STORAGE_NODES"
          value: "30"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - name: storage
        emptyDir: {}
