---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-nfs-pv
  labels:
    group: system
    type: nfs
    role: elasticsearch
spec:
  capacity:
    storage: ${LOGGING_ES_PV_SIZE}
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER}
    path: "${NFS_ROOT}/${CLUSTER_ID}/es"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-nfs-pvc
  namespace: kube-system
  labels:
    group: system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${LOGGING_ES_PV_SIZE}
  selector:
    matchLabels:
      type: nfs
      group: system
      role: elasticsearch

