apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    component: elasticsearch
    role: client
    group: system
    k8s-app: elasticsearch
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "elasticsearch"
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: http
  selector:
    component: elasticsearch
    role: client

