apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: minio1
  name: minio1
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: minio1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: minio1
    spec:
      containers:
      - args:
        - server
        - /data
        image: minio/minio
        imagePullPolicy: Always
        name: minio1
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "4JMA2VSZU3KQZU4Z04YM"
        - name: MINIO_SECRET_KEY
          value: "xYoYJRhG/bLzAXfJtelygzH64I1vGH08MutDtYpp"
        ports:
        - containerPort: 9000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio

