apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  externalIPs:
    - 101.150.3.82
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio
