apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-claim
  labels:
    group: hkube
    type: nfs
    role: minio
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 40.69.222.75
    path: "/srv/vol_nfs/storage/minio"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: default
  labels:
    group: vod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs
      group: hkube
      role: minio

