---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-claim
  labels:
    group: hkube
    type: nfs
    role: minio
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 101.150.4.250
    path: "/vol_vod/SF3/minio"
    #server: ${NFS_HOST}
    #path: "${NFS_ROOT}/SF${CLUSTER_ID}/minio"
