apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-minio-4
  labels:
    group: hkube
    type: nfs
    role: minio-4
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 101.150.4.250
    path: "/vol_vod/CEPH/minio-4"
    #server: ${NFS_HOST}
    #path: "${NFS_ROOT}/SF${CLUSTER_ID}/minio"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-minio-4
  namespace: default
  labels:
    group: vod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      type: nfs
      group: hkube
      role: minio-4

