apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  #labels:
    #k8s-app: fluentd-logging
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        group: system
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: private.registry.rms:5000/fluentd-es:5.5.0.3
        imagePullPolicy: IfNotPresent
        env:
          - name: ELASTICSEARCH
            value: "elasticsearch"
            # within the fluentd image: modify /etc/td-agent/td-agent.conf to contain: host "#{ENV['ELASTICSEARCH']}"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
