apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-system
  labels:
    component: kibana
    kubernetes.io/cluster-service: "true"
    group: system
spec:
  selector:
    component: kibana
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
#  externalIPs:
#    - $VIRTUAL_IP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
  labels:
    component: kibana
    kubernetes.io/cluster-service: "true"
    group: system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kibana
  template:
    metadata:
      labels:
        component: kibana
        group: system
    spec:
      containers:
      - name: kibana
        image: "kibana:5.5.0"
        imagePullPolicy: IfNotPresent
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch:9200"
          - name: "SERVER_BASEPATH"
            value: "https://10.32.10.27:6443/api/v1/namespaces/kube-system/services/kibana/proxy"
        ports:
          - containerPort: 5601
            name: ui
            protocol: TCP
