#!/bin/bash
if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$1

echo_blue 'backup folder deploy-cluster' 

echo ${KUBESPRAY_HOME}
source ${KUBESPRAY_HOME}/env/$1

echo_blue "Backup deploy-cluster folder  without containtainetrs"

cd ~/deploy-cluster

tar --exclude='./containers' -cvf  ~/deploy-cluster.tar.gz .

echo_green 'Done.'
