#!/bin/bash

ENV_NAME=$1

if [[ -z "${ENV_NAME}" ]]; then
  echo "Must Enter Cluster Name"
  exit
fi

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$ENV_NAME

echo_blue "Get Cert for cluster '$ENV_NAME'" 

ansible-playbook -i ${KUBESPRAY_HOME}/env/inventory.$ENV_NAME  ../playbooks/copy-certs.yml

echo_green 'Done.'
