#!/bin/bash

ENV_NAME=$1

if [[ -z "${ENV_NAME}" ]]; then
   echo "Options are"
   ls ../env/*.yml | awk '{ print $1 }'
   echo "Must Enter Cluster Name"
   exit
fi

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$ENV_NAME

echo_blue "Get Cert for cluster '$ENV_NAME'" 

ansible-playbook  -i ${KUBESPRAY_HOME}/env/inventory.$ENV_NAME -e cluster_name=$ENV_NAME ../playbooks/get-certs.yml -vv

echo_green 'Done.'

echo_blue "Get Cert for cluster '$ENV_NAME'" 

kubectl config view --flatten > ~/.kube/config.$ENV_NAME

echo_green 'Done.'

# echo_blue "flatten file cluster '$ENV_NAME'" 

# ansible-playbook  -i ${KUBESPRAY_HOME}/env/inventory.$ENV_NAME -e cluster_name=$ENV_NAME ../playbooks/fetchcerts.yml -vvv

# echo_green 'Done.'

