#!/bin/bash

ENV_NAME=$1

if [[ -z "${ENV_NAME}" ]]; then
   echo "Must Enter Cluster Name"
   exit
fi

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$1

echo_blue 'Cheking kubernetes cluster' 
ansible all -i ../env/inventory.$ENV_NAME -m ping
echo_green 'Done.'
