#!/bin/bash

ENV_NAME=$1

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$1

echo_blue "Installing cluster on $1 ... "

cd ${KUBESPRAY_HOME}

ansible-playbook -b --ask-become-pass -i env/inventory.$1  playbooks/install-keepalived.yml 

echo_green 'Done.'
