#!/bin/bash

ENV_NAME=$1

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

source ${KUBESPRAY_HOME}/env/$1

echo_blue 'shh-copy-id to all Nodes ... '

ansible-playbook -i ${KUBESPRAY_HOME}/env/inventory.$1 ../playbooks/nodes-ssh-copy-id.yml

echo_green 'Done.'

echo_blue 'Pre config  cluster ... '

ansible-playbook -b --ask-become-pass -i ${KUBESPRAY_HOME}/env/inventory.$1 ../playbooks/pre-install.yml

echo_green 'Done.'
