#!/bin/bash
export ENV_NAME=$1

source util

if [[ -z "${ENV_NAME}" ]]; then
   echo "options are"
   ls ../env/*.yml | awk '{ print $1 }'
   echo_red "Must Enter Cluster Name"
   exit
fi

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

echo_blue "Start System Componnent On Cluster $1 ..." 

echo ${KUBESPRAY_HOME}

ansible-playbook -i ../env/inventory.$ENV_NAME -t "Elastic,importvars" -e cluster_name=$ENV_NAME ../playbooks/Start-Helm.yml -v
