#!/bin/bash
ENV_NAME=$1

if [[ -z "${KUBESPRAY_HOME}" ]]; then
  KUBESPRAY_HOME=$( cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd )
  source ${KUBESPRAY_HOME}/scripts/util
fi

echo_blue "Start Cluster $1 ..." 

echo ${KUBESPRAY_HOME}

ansible-playbook -i ../env/inventory.$1 -e $1 --ask-become-pass -b ../playbooks/Start-Cluster.yml
