---

#################################################
# Downloads all images for kubespray Instlation #
#################################################
- hosts: localhost
  tasks:
    - name: downloadall
      with_dict: "{{ downloads }}"
      include_role:
        name: download
      vars:
        local_release_dir: /tmp/mykube
        download_localhost: True
        download_run_once: True
        # file: "{{ downloads.etcd }}"
        file: "{{ item.value|combine({'enabled':True}) }}"
        key: "{{ item.key }}"
        deploy_netchecker: False
        kube_network_plugin: canal
        docker_bin_dir: /usr/bin
  vars_files:
    - inventory/group_vars/k8s-cluster.yml
    - roles/download/defaults/main.yml