---

- hosts: kube-master[0]
  gather_facts: no
  become: yes
  
  tasks:
    - fetch:
        src: "/etc/kubernetes/ssl/{{ item }}.pem"
        dest: "{{ playbook_dir }}/../kubespray/kubectl/{{ item }}.pem"
        flat: True
      with_items:
        - admin-{{ inventory_hostname }}-key
        - admin-{{ inventory_hostname }}
        - ca
    - name: export hostname
      set_fact:
        kubectl_name: "{{ inventory_hostname }}"

- hosts: kube-master[0]
  gather_facts: yes

  vars:
    kubectl_name: "{{ hostvars[groups['kube-master'][0]].kubectl_name }}"
  tasks:

  - name: " Copy admin.config file to ~/.kube/config to hosts that don't have it"
    copy:
      src: "~/deploy-cluster/env/artifacts/admin.conf"
      dest: "/home/ubadmin/admin.conf" 
      group: "ubadmin"
      mode: "640"
      owner: "ubadmin"

  - name: Gen_certs | copy certs generation script
    copy: 
      src: "make-ssl.sh"
      dest: "{{ kube_script_dir }}/make-ssl.sh"
      mode: 0700
    run_once: yes
    delegate_to: "{{groups['kube-master'][0]}}"
    when: gen_certs|default(false)
