---

#################################################
#  Downloads System Images Dockers local folder #
#################################################
- hosts: localhost
  tasks:
    - name: search images on files 
      shell: |
        export KUBESPRAY_HOME=/home/$USER/deploy-cluster
        export pattern=".*image:\s*\/\(.*\)$"
        grep -rP "image:\s*" ${KUBESPRAY_HOME}/deployments   | sed -n 's/'".*image:\s\(.*\)$"'/\1/p' | sort -u
      tags: pull-images
      register: list_items_found
    - debug: var=list_items_found
          
    - name: pull images 
      command: docker pull {{ item }}
      vars: 
        DOCKER_REGISTRY_HOST: "cir-srv01"
      with_items: "{{ list_items_found.stdout_lines }}"
    
    - name: save images
      vars: 
        itemx: "{{ item | regex_replace('\\/','_') | regex_replace('\\:','-') }}"
        DOCKER_REGISTRY_HOST: "cir-srv01"
      command: docker save -o {{ itemx }}.tar  {{ item }}
      with_items: "{{ list_items_found.stdout_lines  }}"
