---

- hosts: kube-master[0]
  gather_facts: no
  become: no
  tasks:
    - name: fetching the config file from first master
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config.{{ cluster_name }}"
        flat: yes
- hosts: localhost
  become: no
  tasks:
    - stat:
        path: ~/.kube/config
      register: configfile
    - name: switch context to "{{ cluster_name }}"
      shell: |
        KUBECONFIG=~/.kube/config."{{ cluster_name }}":~/.kube/config kubectl config view --flatten > ~/.kube/config.tmp
        rm ~/.kube/config
        cp ~/.kube/config."{{ cluster_name }}" ~/.kube/config
        #rm ~/.kube/config.tmp
        #kubectl config use-context "{{ cluster_name }}"
      tags: switchcontext
      when: configfile.stat.exists

