---

- hosts: localhost
  name: Labeling Nodes on Cluster
  become: no
  vars_prompt:
    - name: "cluster_name"
      prompt: "Type The Cluster Name you are  working"
      configrm: yes
  
  tasks:
  - name: Inport Vars form Cluster Config yaml
    debug:
      msg="{{ lookup('env','ENV_NAME') }}"
  - include_vars: ../env/{{ lookup('env','ENV_NAME') }}.yml
  - include_vars: "../env/{{ cluster_name }}.yml"

  - name: Debug Test2
    debug:
      msg="You are Working On {{ cluster_name }} Cluster"

  - name: Debug ENV_NAME 
    debug:
      msg="{{ lookup('env','ENV_NAME') }}"  

  - name: add lables to nodes  for Cluster "{{ cluster_name }}"
    command: kubectl lable nodes --overwrite=true  ${nideIP} master=master worker=worker frontend=frontend backend=backend
    tags: labeling
