---

- hosts: localhost
  name: Configur file for Cluster
  become: no
  vars_prompt:

    - name: "USERNAME"
      prompt: "Enter Your User Name"
      default: "ubadmin"

    - name: "CLUSTER_ID"
      prompt: "Cluster Name to work on"
      confirm: yes
      default: "SF1"
     
  tasks:
  - name: Debug Test
    debug:
      msg:
       - "{{ CLUSTER_ID }}"
       - "{{ USERNAME }}"
  - name:
    lineinfile:
      path: '{{ home_directory }}/.bashrc'
      state: present
      line: 'source <(kubectl completion bash)'
  - name: 
    lineinfile:
      path: '{{ home_directory }}/.bashrc'
      state: present
      line: 'source ~/K8S/env/k8s_env'
  - name: 
    lineinfile:
      path: '{{ home_directory }}/.bashrc'
      state: present
      line: 'export NS=--namespace=kube-system'
  vars:
    home_directory: '/home/{{ USERNAME }}'
