---

#- hosts: all
#  name: Installing chrony
#  become: yes
#  roles:
#   - ../roles/chrony
#  tags:
#    - chrony

#- hosts: kube-node
#  become: yes
#  roles:
#    - ../roles/nfs
#  tags:
#    - nfs-common

#- hosts: kube-node
#  become: yes
#  roles:
#    - ../roles/python-netaddr
#  tags:
#    - python-netaddr
#- hosts: all
#  become: yes
#  roles:
#    - ../roles/kubectl
#  tags:
#    - kubectl
- hosts: new
  become: yes
  roles:
    - ../roles/docker-ce
  tags:
    - docker-ce
