---

- hosts: all
  name: Installing ntp 
  become: yes
  roles:
   - ../roles/ntp
  tags:
    - ntp

- hosts: kube-node
  become: yes
  roles:
    - ../roles/nfs
  tags:
    - nfs-common

- hosts: kube-node
  become: yes
  roles:
    - ../roles/python-netaddr
  tags:
    - python-netaddr
