---

- hosts: localhost
  name: Installing Cluster
  become: no
  vars_prompt:
    - name: "cluster_name"
      prompt: "Cluster Name to work on"
      default: "SF1"

  tasks:
  - name: Debug Test
    debug:
      msg="{{ cluster_name }}"

- import_playbook: pre-install.yml
