--- 

# Cluster Info

CLUSTER_ID: dev

# keepalived 

INSTALL_KEEPALIVED: True
interface_network: eth0
cluster_id: 3
virtual_cluster_ip: 10.32.10.27

# nfs server 

NFS_SERVER: 10.32.10.26
NFS_ROOT: /srv/vol_nfs
USE_PERSISTANT_VOLUMES: True

##INSTALL_NFS_HOST: False

url_username: kube
url_password: SoundFactory

# Kibana 
KIBANA_EXTERNAL_IP: 10.32.10.27

# Elastic Defualt Configuration 

LOGGING_ES_PV_SIZE: 100Gi
LOGGING_ES_REPLICAS_MASTER: 1
LOGGING_ES_REPLICAS_CLIENT: 1
LOGGING_ES_REPLICAS_DATA: 2
LOGGING_ES_MINIMUM_MASTERS: 1
LOGGING_ES_JAVA_HEAP_SIZE: 2g

# Prometheus Defualt Configuration

PROM_PV_SIZE: 100Gi

# Nodes Labels 

LABLES:
  - node: node12
    labels:
      - api
      - "reverse-proxy"
      - worker
      - core
      - "third-party"
  - node: node13
    labels:
      - worker
      - core
      - "third-party"
  - node: node14
    labels:
      - worker
      - core
      - "third-party"
  - node: node15
    labels:
      - worker
      - core
      - "third-party"
  - node: node16
    labels:
      - worker
      - core
      - "third-party"
  - node: node17
    labels:
      - worker    
      - worker
      - core
      - "third-party"
