env:
  default_storage: 's3'
global:
  production: true
  clusterName: kube12
  # registry: docker.io/
  registry: ""
  storage:
    minio:
      url: http://10.32.10.24:9000 
      access_key: agambstorage
      secret_key: 234eqndbpuCkGtH85KSyK/xAv3xuqdOpM3fKOLYlrSerpdKoG1FYy3kh6ArceL+yDwTvQOgs47xYO/ktnNzEeg==
    fs:
      pvc: 
         name: 'hkube-storage'
         capacity: '10Gi'
         nfs_server: 'nfs-server'
         nfs_root: '/srv/vol_nfs'
      base_directory: '/hkubedata'
