{
 "title": "HKube General",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "labelSelector": "alertname, summary", "target": "Query", "type": "table" }
   ]
  },
  { "title": "Pipelines (jobs)", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 6 }, "content": "# title" },
  { "title": "Algorithms (tasks)", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 6 }, "content": "# title" },
  {
   "title": "Pipelines Time in  Queue Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pipeline_driver_queue_time_in_queue_histogram_bucket[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pipeline_driver_queue_time_in_queue_histogram_bucket[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Pipelines Total Runtime Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pipeline_driver_pipelines_net_histogram_bucket[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(pipeline_driver_pipelines_net_histogram_bucket[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Algorithms Time in  Queue Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Algorithms Total Runtime Percentiles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(worker_net_histogram_bucket[5m])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_net_histogram_bucket[5m])) by (le))",
     "legendFormat": "95%"
    }
   ]
  },
  {
   "title": "Number  of Queued Pipelines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "pipelines" }
   ],
   "targets": [
    {
     "expr": "sum(pipeline_driver_queue_amount_gauge)",
     "legendFormat": "pipelines queue size"
    }
   ]
  },
  {
   "title": "Pipelines Start Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pipeline_driver_queue_counter_counter[5m])) * 60",
     "legendFormat": "started"
    }
   ]
  },
  {
   "title": "Number of Queued Algorithms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "algorithms" }
   ],
   "targets": [
    {
     "expr": "sum(algorithm_queue_queue_amount_gauge)",
     "legendFormat": "alg_queue_size"
    }
   ]
  },
  {
   "title": "Algorithms Start Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_started_counter[5m])) * 60",
     "legendFormat": "started"
    }
   ]
  },
  {
   "title": "Pipelines Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_server_pipelines_gross_counter{status='completed'}[5m])) * 60",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Pipelines Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "pipelines / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_server_pipelines_gross_counter{status='failed'}[5m])) * 60",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Algorithms Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_succeeded_counter[5m])) * 60",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "Algorithms Failure Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_failed_counter[5m])) * 60",
     "legendFormat": "failed"
    }
   ]
  }
 ]
}