{
 "title": "HKube Algorithms",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Queued Algorithms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(algorithm_queue_queue_amount_gauge) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Start Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_started_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_succeeded_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Failure Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "algorithms / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(worker_failed_counter[5m])) by (algorithm_name) * 60",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Average Time in Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(algorithm_queue_time_in_queue_histogram_sum) by (algorithm_name) / sum(algorithm_queue_time_in_queue_histogram_count) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Median Time in  Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms 95% Percentile Time in  Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(algorithm_queue_time_in_queue_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Average Total Runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(worker_net_histogram_sum) by (algorithm_name) / sum(worker_net_histogram_count) by (algorithm_name)",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms Median Total Runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(worker_net_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "Algorithms 95% Percentile Total Runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(worker_net_histogram_bucket[5m])) by (le, algorithm_name))",
     "legendFormat": "{{algorithm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Algorithms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(\nmax(kube_pod_labels{label_algorithm_name!~\"\"}) by (label_algorithm_name, pod)\n                   * on(pod)\n                   group_right(label_algorithm_name)\n                   label_replace(\n                       sum by(pod_name) (\n                           rate(container_cpu_usage_seconds_total{container_name=\"algorunner\"}[5m])\n                       ), \"pod\", \"$1\", \"pod_name\", \"(.+)\")\n                   ) by (label_algorithm_name)",
     "legendFormat": "{{label_algorithm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Algorithms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "sum(\nmax(kube_pod_labels{label_algorithm_name!~\"\"}) by (label_algorithm_name, pod)\n                   * on(pod)\n                   group_right(label_algorithm_name)\n                   label_replace(\n                       sum by(pod_name) (\n                           container_memory_working_set_bytes\n                       ), \"pod\", \"$1\", \"pod_name\", \"(.+)\")\n                   ) by (label_algorithm_name) / 1000",
     "legendFormat": "{{label_algorithm_name}}"
    }
   ]
  }
 ]
}